type CarItem @model(name: "carItems", source: "carItems") {
  id: String!
  registration: String
  car_overview: CarOverview
  safety_features: [String]
  interior_features: [String]
  performance_features: [String]
  exterior_features: [String]
  pictures: [String]
}

type CarOverview {
  brand: String
  model: String
  price: Int
}
