type CarItem @model(name: "carItems", source: "carItems") {
  id: String!       # partition key mag ook hier
  registration: String
  car_overview: CarOverview
}

type CarOverview {
  brand: String
  model: String
  price: Int
}
